# Generated by Django 4.2.1 on 2023-05-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('title',)},
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.URLField(default='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='title', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(default='other', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='first_name', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='image_url',
            field=models.URLField(default='url', verbose_name='Image URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='last_name', max_length=30),
            preserve_default=False,
        ),
    ]
